# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        :title

# Setup
title:            Ash Ganatra
tagline:          'Scrum Master / IT Consultant'
description:      'A place where I am composing my thoughts and experiences in the form of a blog :)'
url:              http://ashga.github.io

author:
  name:           'Ash Ganatra'
  url:            https://blog.ashga.io

paginate:         5

