# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            ashga
tagline:          'Web/Mobile App Consultant'
description:      'A place where I am composing my thoughts and experiences in the form of a good old fashion blog :)'
url:              http://ashga.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/ashga

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ashga/ashga.github.com
